# Generated by Django 5.0.2 on 2024-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quest_can_pause',
            new_name='guests_can_pause',
        ),
    ]
